name: Build-Test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install ncurses
      run: sudo apt install -y libncurses-dev pkgconf

    - name: Compile
      run: gcc -Wall -Werror src/*.c `pkg-config --cflags --libs ncurses`
