name: Build-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install ncurses
      run: sudo apt install -y libncurses-dev

    - name: cd to src
      run: cd src

    - name: Compile
      run: g++ -Wall -Werror -lncurses keycode.cpp
